services:

  mysql:

    image: mysql:8.0

    container_name: ctcl-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ctcl_2026
      MYSQL_DATABASE: ctcl_db

    ports:
      - "3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/ctcl_db.sql:/docker-entrypoint-initdb.d/ctcl_db.sql

  ctcl-web:

    build: .

    container_name: ctcl-web

    depends_on:
      - mysql

    ports:
      - "8000:8000"

    env_file:
      - .env

    restart: unless-stopped

volumes:

  mysql_data: